### ISSUE TITLE
AniList Plan to Watch List Load Error

### ISSUE THREAD

**Issue by SkittlemanAeo** [Goldenfreddy0703/Otaku-Testing#13]
When I click on Plan to Watch for AniList I get the error shown in the picture below. The list was working, but I have not used it for a few days so I don't know if it has to do with the latest update or not. The add-on is up-to-date. Other AniList lists work, such as Current or Paused. I have cleared the cache and rebuilt the database but the issue persists. I have also logged out and in to AniList with the same results.

![Otaku Error](https://github.com/user-attachments/assets/b67ffb6d-7cd8-44b4-8888-7e046024bdb1)

**Comment by Goldenfreddy0703** [comment]
Ahh I recently did some changes in watchlist try rebuilding the database and see if that fixes it.

**Comment by SkittlemanAeo** [comment]
Though I mentioned rebuilding the database didn't work before, I went ahead and tried it again since you requested it. After rebuilding the database I get the same error.

**Comment by Goldenfreddy0703** [comment]
Oh that's a bit odd, would you mind reauthorizing in anilist and maybe giving me a log maybe.

**Comment by SkittlemanAeo** [comment]
I have reauthorized and it still doesn't work. It's strange because it's ONLY the Plan to Watch list, every other list works. I'll get and provide a log later today when my fiancee wakes up.

**Comment by SkittlemanAeo** [comment]
I have uploaded a log to the link below. The relevant error starts at line 560.

https://paste.kodi.tv/xodayimonu

**Comment by Goldenfreddy0703** [comment]
Hey so had to delete your log cause it contained your public ip address but I saved it on my browser, will look into it when I get back.

**Comment by SkittlemanAeo** [comment]
I can't believe I didn't pay attention to that, I know way better than leaving my public IP visible. Thank you for catching that!

**Comment by Goldenfreddy0703** [comment]
Hey @SkittlemanAeo , we released a version that should hopefully fix this error but if not, upload us a log and we can see which anime is causing this. Thanks

**Comment by SkittlemanAeo** [comment]
The new version fixed my error and it is now working as expected. Thank you for the rapid response!
