### ISSUE TITLE
One piece fish man island

### ISSUE THREAD

**Issue by GitHubSand** [Goldenfreddy0703/Otaku-Testing#14]
It's showing up on otaku but it opens regular OP

**Comment by joezito129** [comment]
what device are you using

**Comment by GitHubSand** [comment]
Xbox

**Comment by Goldenfreddy0703** [comment]
Ahh that could explain it, sometimes xbox or apple are always the ones that have most issues. One workaround you could probably do is authorize on a different device and then use the import and export feature so that way, you can transfer your settings and all.

**Comment by GitHubSand** [comment]
I've tried to do a back up like that but I decided to drop it Xbox makes things just annoying, I'll just add magnets to cloud and watch it that way thanks for the help

**Comment by GitHubSand** [comment]
It's working now thanks
