### ISSUE TITLE
Fanart for Anilist

### ISSUE THREAD

**Issue by potatowe** [Goldenfreddy0703/Otaku-Testing#2]
Anilist doesn't have fanart or clearlogo for some reason
![image](https://github.com/user-attachments/assets/a5f2e0a1-1b81-4e39-ba20-ca210d9da023)

For comparison other widgets work fine:
![image](https://github.com/user-attachments/assets/722421ca-c391-43e0-9f36-5c41e5688d28)

This seems to only be a problem in the testing repo (I reverted back to the original repo and it looked fine) and not a problem with the skin

**Comment by Goldenfreddy0703** [comment]
Hey there, sorry this took forever but i finally figured out a way to add fanart to Anilist and all other watchlist. Our latest version should be out so please rebuild database and give it a try and tell me if this fixed your issue, if not then we will look into this further. 

Thanks
