### ISSUE TITLE
Can't play a certain video

### ISSUE THREAD

**Issue by GitHubSand** [Goldenfreddy0703/Otaku-Testing#3]
https://github.com/user-attachments/assets/d3fab8b0-5d91-4a16-a69f-1e75e88d3c6a

**Comment by GitHubSand** [comment]
Yes it still happens, it works fin on the RD website

**Comment by Goldenfreddy0703** [comment]
Mmmmm would you mind giving me the link to put that in my cloud so I can test on my end?

**Comment by GitHubSand** [comment]
https://1337x.to/torrent/5756272/One-Piece-0001-1071-Movies-Specials-BD-CR-Dual-Audio-1080p-HEVC-10bit-x265-AAC-Multi-Sub-Anime-Time/

**Comment by Goldenfreddy0703** [comment]
Thanks will have this tested very soon.

**Comment by Goldenfreddy0703** [comment]
Hey sorry this took forever but we manage to fix your issue with One Piece so hopefully should be fixed now.
Huge thanks to @joezito129 for fixing this.

**Comment by GitHubSand** [comment]
Thanks🙏
