### ISSUE TITLE
Watchlist won't update automatically (also how do you get the Playing Next dialog?)

### ISSUE THREAD

**Issue by potatowe** [Goldenfreddy0703/Otaku-Testing#4]
When using the next up widget I don’t get the ‘playing next’ dialogue which I enabled in Otaku settings and it doesn’t auto scrape the next episode either. It also doesn’t update my watchlist automatically, so I have to update it manually in the context menu. How would I get these to work automatically ?

**Comment by Goldenfreddy0703** [comment]
Hey there, i just wanna make sure but is Watchlist updating for you now? Also have you reauthorized Watchlist?

**Comment by zambux** [comment]
> Ok so this is quite dumb but to get next up working, you would have to go to kodi's player settings and have the first option set to episodes.
> 
> Reason why users have todo this unfortunately is cause we are utilizing the Kodi Playlist cause building our own is buggy and all.

Could you explain better how to do this? Where to go for these settings?

**Comment by Goldenfreddy0703** [comment]
Hey @potatowe sorry to bother you but have you manage to get your Watchlist to update for next-up without using the widget?

**Comment by Goldenfreddy0703** [comment]
Hey so im gonna go ahead and close this but if issues still persist, we will open this back up.
Thanks
