### ISSUE TITLE
Otaku search path for Arctic Fuse 2

### ISSUE THREAD

**Issue by potatowe** [Goldenfreddy0703/Otaku-Testing#5]
I'm trying to add Otaku search to AF2 using [this](https://github.com/jurialmunkey/skin.arctic.horizon.2/discussions/1014#discussioncomment-8424602), but it comes up with an  error
![image](https://github.com/user-attachments/assets/8e4b6e95-f504-4de7-a50b-86a27b253f10)
Is there an updated path?

**Comment by Goldenfreddy0703** [comment]
Hey so in this next release thats going to happen very soon, set your custom search path to this:
`plugin://plugin.video.otaku.testing/search/`

**Comment by Goldenfreddy0703** [comment]
Hey so just pushed out a huge release, just make sure to change the custom search path i have above. 
Anyway gonna close this, if you encounter any issues related to this, please feel free to reply and we will open this back up.
Thank you
