### ISSUE TITLE
context.otaku

### ISSUE THREAD

**Issue by zambux** [Goldenfreddy0703/Otaku-Testing#6]
is just with me or since the version 5.1.14, contextmenu stopped working

**Comment by Goldenfreddy0703** [comment]
could be you, what version of the context menu are you running?

**Comment by Goldenfreddy0703** [comment]
So funny story, when i was renaming the whole addon folder, i completely forgot about the context menu and i never noticed during testing. Should be fixed in the next release very soon. 

Thank you for pointing this out!!!!

**Comment by Goldenfreddy0703** [comment]
Hey so i just pushed a release, latest version should fix the issue with context menus. again, thank you for pointing this out.
